exclude: |
    (?x)^(
        README.md|
        LICENSE|
        tests/ymls/others/
    )
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
    - repo: https://github.com/pycqa/flake8
      rev: 7.3.0
      hooks:
        - id: flake8
          args:
            - "--max-line-length=512"
    - repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
        - id: isort
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
        - id: black
          args: # arguments to configure black
            - --line-length=512
    - repo: local
      hooks:
        - id: pyright
          name: pyright
          entry: pyright
          language: node
          pass_filenames: false
          types: [python]
          additional_dependencies: ['pyright@1.1.247']
